src/pets2/config/routes.rb
Pets::Application.routes.draw do
  resources :foster_parents

  resources :line_items

  resources :considerations

  resources :foster_parents do
    collection do
      get :who_fostered
    end
  end
  
  resources :fosters

  get "adoption/index"
  resources :animals

    root 'adoption#index', as: 'adoption'

end

src/pets2/app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :animal
  belongs_to :consideration
end

src/pets2/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentConsideration
  before_action :set_consideration, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    animal = Animal.find(params[:animal_id])
    @line_item = @consideration.add_animal(animal.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to adoption_url }
		format.js { @current_item = @line_item }
        format.json { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:animal_id)
    end
end

src/pets2/app/helpers/line_items_helper.rb
module LineItemsHelper
end

src/pets2/app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :animal_id %><br>
    <%= f.text_field :animal_id %>
  </div>
  <div class="field">
    <%= f.label :consideration_id %><br>
    <%= f.text_field :consideration_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/pets2/app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr id="current_item">
<% else %>
<tr>
<% end %>
  <td><%= line_item.animal.name %></td>
</tr>

src/pets2/app/views/line_items/create.js.erb
$('#notice').hide();

if ($('#consideration tr').length == 0) { $('#consideration').show('blind', 1000); }

$('#consideration').html("<%= escape_javascript render(@consideration) %>");

$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#f4a460'}, 1000);

src/pets2/app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

src/pets2/app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Animal</th>
      <th>Consideration</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.animal %></td>
        <td><%= line_item.consideration %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

src/pets2/app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

src/pets2/app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Animal:</strong>
  <%= @line_item.animal %>
</p>

<p>
  <strong>Consideration:</strong>
  <%= @line_item.consideration %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>