src/pets2/config/routes.rb
Pets::Application.routes.draw do
  resources :foster_parents

  resources :line_items

  resources :considerations

  resources :foster_parents do
    collection do
      get :who_fostered
    end
  end
  
  resources :fosters

  get "adoption/index"
  resources :animals

    root 'adoption#index', as: 'adoption'

end

src/pets2/app/models/foster.rb
class Foster < ActiveRecord::Base
end

src/pets2/app/controllers/fosters_controller.rb
class FostersController < ApplicationController
  before_action :set_foster, only: [:show, :edit, :update, :destroy]
  @@foster_animal = Animal.first
  # GET /fosters
  # GET /fosters.json
  def index
    @fosters = Foster.all
  end

  # GET /fosters/1
  # GET /fosters/1.json
  def show
	@animals = Animal.find(@@foster_animal)
  end

  # GET /fosters/new
  def new
    @foster = Foster.new
  end

  # GET /fosters/1/edit
  def edit
  end

  # POST /fosters
  # POST /fosters.json
  def create
	@animals = Animal.find(params[:animal_id])
    @foster = Foster.new(foster_params)

	@@foster_animal = params[:animal_id]
    respond_to do |format|
      if @foster.save
        format.html { redirect_to @foster }
        format.json { render action: 'show', status: :created, location: @foster }
      else
        format.html { render action: 'new' }
        format.json { render json: @foster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fosters/1
  # PATCH/PUT /fosters/1.json
  def update
    respond_to do |format|
      if @foster.update(foster_params)
        format.html { redirect_to @foster, notice: 'Foster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @foster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fosters/1
  # DELETE /fosters/1.json
  def destroy
    @foster.destroy
    respond_to do |format|
      format.html { redirect_to fosters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foster
      @foster = Foster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foster_params
      params[:foster]
    end
end

src/pets2/app/helpers/fosters_helper.rb
module FostersHelper
end

src/pets2/app/views/fosters/_form.html.erb
<%= form_for(@foster) do |f| %>
  <% if @foster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foster.errors.count, "error") %> prohibited this foster from being saved:</h2>

      <ul>
      <% @foster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/pets2/app/views/fosters/edit.html.erb
<h1>Editing foster</h1>

<%= render 'form' %>

<%= link_to 'Show', @foster %> |
<%= link_to 'Back', fosters_path %>

src/pets2/app/views/fosters/index.html.erb
<h1>Listing fosters</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fosters.each do |foster| %>
      <tr>
        <td><%= link_to 'Show', foster %></td>
        <td><%= link_to 'Edit', edit_foster_path(foster) %></td>
        <td><%= link_to 'Destroy', foster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foster', new_foster_path %>

src/pets2/app/views/fosters/new.html.erb
<h1>New foster</h1>

<%= render 'form' %>

<%= link_to 'Back', fosters_path %>

src/pets2/app/views/fosters/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Foster Agreement</h1>

<p> By fostering this pet you are agreeing to take the proper care necessary for this animal. If you are found to mistreat this animal in any way, you will be thrown in jail and no one will like you anymore. So just be a good person, mmkay? </p>

<% animal = @animals %>
<div class="entry">
	<h3><%= animal.name %></h3>
	<%= image_tag(animal.image_url) %>
	<%= sanitize(animal.habits) %>
	<div class="info_line">
		<span class="breed">Breed: <%= animal.breed %></span>
		<span class="gender">Gender: <%= animal.gender %></span>
		<span class="age">Age: <%= animal.age %></span>
	</div>
	<div class="button_line">
		<%= link_to "Confirm", controller: "foster_parents", action: "new", animal_id: @animals%>
		<%= link_to "Cancel", adoption_path %>
	</div>
</div>